name: Deployment

on:
  push:
    branches:
      - "$default-branch"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./buildtools

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "13"
        check-latest: true

    - run: npm ci
    - run: npx gulp check
